openapi: 3.0.3
info:
  title: Powerrank API
  version: 1.0.0
servers:
  - url: https://{{placeholder}}/api/powerrank
tags:
  - name: rankings
    description: Operations on rankings
paths:
  /global_rankings:
    get:
      tags:
        - rankings
      summary: Get paged global rankings
      operationId: getGlobalRankings
      parameters:
        - name: number_of_teams
          in: query
          schema:
            type: integer
            format: int64
        - name: page_number
          in: query
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
  /team_rankings:
    get:
      tags:
        - rankings
      summary: Get team rankings
      operationId: getTeamRankings
      parameters:
        - name: team_ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '400':
          description: Invalid ID supplied
  /tournament_rankings/{tournament_id}:
    get:
      tags:
        - rankings
      summary: Get tournament participant rankings
      operationId: getTournamentRankings
      parameters:
        - name: tournament_id
          in: path
          required: true
          schema:
            type: string
        - name: stage
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '400':
          description: Invalid ID supplied
  /tournaments:
    get:
      tags:
        - Tournaments
      summary: Get all tournaments
      operationId: getTournaments
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tournament'
  /teams:
    get:
      tags:
        - Teams
      summary: Get all teams
      operationId: getTeams
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
components:
  schemas:
    Team:
      type: object
      properties:
        id:
          type: string
          example: 178123987129837232
        name:
          type: string
          example: team powerrank
        points:
          type: integer
          format: int64
          example: 123
      additionalProperties: false
    Tournament:
      type: object
      properties:
        id:
          type: string
          example: 123
        name:
          type: string
          example: worlds2021
      additionalProperties: false